services:
    api:
        build: .
        env_file: .env
        ports:
            - 8000:8000
        depends_on:
            - db
        develop:
            watch:
                - action: sync
                  path: ./
                  target: /app
                  ignore:
                      - node_modules
                      - dist
                      - mongo-data

                - action: rebuild
                  path: package.json

    db:
        image: mongo
        restart: always
        env_file: .env
        command: mongod --quiet --setParameter diagnosticDataCollectionEnabled=false
        volumes:
            - ./mongo-data:/data/db
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
            - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}

volumes:
    mongo-data:
