# binds to an external network of the microservice architecture
services:
    auth-service:
        container_name: auth-service-sg
        build:
            context: .
            dockerfile: Dockerfile
        env_file: .env
        expose:
            - 8000
        networks:
            - microservices
        depends_on:
            - auth-db
        volumes:
            - ./src:/app/src
            - /node_modules
        develop:
            watch:
                # - action: sync
                #   path: ./
                #   target: /app
                #   ignore:
                #       - node_modules
                #       - dist
                #       - mongo-data
                #       - scripts/init-db.js

                - action: sync+restart
                  path: ./src/config
                  target: /app/src/config
                - action: rebuild
                  path: package.json

    auth-db:
        image: mongo
        container_name: auth-db-sg
        build:
            context: .
            dockerfile: db.Dockerfile
        restart: unless-stopped
        logging:
            driver: none #disable logging
        env_file: .env
        expose:
            - 27017
        networks:
            - microservices
        volumes:
            - ./mongo-data:/data/db
        environment:
            - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}

    auth-db-admin:
        image: mongo-express
        container_name: auth-db-admin-sg
        logging:
            driver: none #disable logging
        depends_on:
            - auth-db
        env_file: .env
        ports:
            - 8002:8000
        networks:
            - microservices
        environment:
            - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_INITDB_ROOT_USERNAME}
            - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
            - ME_CONFIG_MONGODB_URL=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@auth-db:27017/
            - ME_CONFIG_BASICAUTH=false

volumes:
    mongo-data:
